on:
  repository_dispatch:
    types: ["upload_artifact"]

name: Release and Upload Asset

jobs:
  upload:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update internal modules
        run: |
          npm ci
          npm install @akashic/akashic-engine@latest --save-exact
          npm install @akashic-extension/akashic-box2d@latest --save-exact
          npm install @akashic-extension/akashic-label@latest --save-exact
          npm install @akashic-extension/akashic-timeline@latest --save-exact
          npm run build
      - name: Bump package version
        run: npm version patch --no-git-tag-version
      - name: Get version of package.json
        id: version
        run: |
          VERSION=`cat package.json | jq -r '.devDependencies["@akashic/akashic-engine"]'`
          echo "::set-output name=VERSION::$VERSION"
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: output_${{ steps.version.outputs.VERSION }}
          path: ./dist
      - name: Create commits
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git add -A
          git commit -m "Update to ${{ steps.version.outputs.VERSION }}"
      - name: Get workflow url
        id: workflow
        run: echo "::set-output name=WORKFLOW_URL::$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: update to akashic-engine@${{steps.version.outputs.VERSION}}
          branch: upload_artifact_file/${{steps.version.outputs.VERSION}}
          body: |
            ## このPullRequestが解決する内容
            akashic-engine を ${{steps.version.outputs.VERSION}} に更新します。
            ## 動作確認方法
            [こちら](${{ steps.workflow.outputs.WORKFLOW_URL }}) から **output_${{ steps.version.outputs.VERSION }}.zip** をダウンロードして、手元で実行できるかを確認してください。
          delete-branch: true
